name: assignment_01_cipherschools
description: Assignment-01-CipherSchools

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  flutter_rating_stars: ^1.0.3+4
  card_swiper: ^2.0.4
  animated_number: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/main_logo.png
    - assets/images/discord.png
    - assets/images/python.png
    - assets/images/free_banner.png
    - assets/images/rating_person1.png
    - assets/images/rating_person2.png
    - assets/images/rating_person3.png
    - assets/images/rating_person4.png
    - assets/images/girl_learning.png
    - assets/images/girl_teaching.jpg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
